export enum SourceType {
  MOCK_SIEM = 'MOCK_SIEM',
  MOCK_EDR = 'MOCK_EDR',
  MOCK_IAM = 'MOCK_IAM'
}

export enum Severity {
  INFO = 'INFO',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum Category {
  AUTHENTICATION = 'AUTHENTICATION',
  MALWARE = 'MALWARE',
  PRIVILEGE = 'PRIVILEGE',
  NETWORK = 'NETWORK',
  POLICY = 'POLICY',
  CONFIGURATION = 'CONFIGURATION',
  DATA_ACCESS = 'DATA_ACCESS',
  ENDPOINT = 'ENDPOINT',
  OTHER = 'OTHER'
}

export enum EventStatus {
  OPEN = 'OPEN',
  INVESTIGATING = 'INVESTIGATING',
  RESOLVED = 'RESOLVED',
  FALSE_POSITIVE = 'FALSE_POSITIVE'
}

export enum UserRole {
  ADMIN = 'ADMIN',
  ANALYST = 'ANALYST',
  VIEWER = 'VIEWER'
}

export enum HistoryAction {
  INGESTED = 'INGESTED',
  DEDUPLICATED = 'DEDUPLICATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  ASSIGNED = 'ASSIGNED',
  UNASSIGNED = 'UNASSIGNED',
  NOTE_ADDED = 'NOTE_ADDED',
  NOTE_EDITED = 'NOTE_EDITED',
  RESOLVED = 'RESOLVED',
  REOPENED = 'REOPENED'
}
